backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/static-assets/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/static-assets/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - label: "Site Info"
    name: "site info"
    files:
      - label: "Progressive Web App"
        name: "PWA"
        file: "_data/pwa.yml"
        fields: 
          - {label: "Enable PWA", name: enablePWA, widget: boolean, default: true, hint: "Determines if the site will register a Service Worker" }
          - {label: "Name", name: name, widget: string, hint: "The name of you PWA" }
          - {label: "Short Name", name: shortName, widget: string, hint: "The short name of your PWA. Usually displayed under the icon if installed to users home screen" }
          - {label: "Start URL", name: "startUrl", widget: string, hint: "The URL which the user will start from when launching the PWA. Include a query string param if you want to track launches from PWA" }
          - {label: "Display", name: "display", widget: select, options: ["standalone", "fullscreen", "minimal ui", "browser" ] }
          - {label: "Background Colour", name: "bgColour", widget: string, hint: "Loading colour of app when launching" }
          - {label: "Theme Colour", name: themeColour, widget: string, hint: "Defines the default theme color for an application." }
          - {label: "Scope", name: "scope", widget: string, hint: "Defines the navigation scope of this website's context." }
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - {label: name, name: name, widget: string}
          - {label: bio, name: bio, widget: text}
      - label: "Site Settings"
        name: "settings"
        file: "_data/settings.yml"
        fields:
          - {label: Title, name: title, widget: string, hint: "The name of your site" }
          - {label: Domain, name: domainname, widget: string, hint: "The url of your site. Example: https://mysite.com" }
          - {label: "Twitter Handle", name: twitter, widget: string, hint: "Your Twitter handle for Rich Cards" }
          - {label: "Open Grpah", name: opengraph, widget: boolean, default: true, hint: "This is used for rich cards on Twitter and the like" }
          - {label: Webmentions, name: webmention, widget: boolean, default: false }
          - {label: Bootstrap, name: bootstrap, widget: boolean, default: false }
      - label: "Social Media"
        name: "social"
        file: "_data/social.yml"
        fields:
          - label: platform
            name: platform
            widget: list
            fields:
              - {label: Name, name: name, widget: string, hint: "The name of the platform, i.e. Twitter, Facebook" }
              - {label: URL, name: url, widget: string, hint: "The full address for your profile, i.e. https://twitter.com/jshvgt" }
              - {label: Class, name: class, widget: string, hint: "The microformat for the link type (u-tel, u-url, u-email)" }
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    description: >
      Traditional blog posts.
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "Categories", name: "categories", widget: "string", default: "blog"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Author", name: "author", widget: "text"}
      - {label: "permalink", name: "permalink", widget: "text", default: "/posts/:categories/:title/"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
  - name: "notes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Notes" # Used in the UI, ie.: "New Post"
    description: >
      Short notes.
    folder: "_posts/notes"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "Categories", name: "categories", widget: "string", default: "note"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Author", name: "author", widget: "text"}
      - {label: "permalink", name: "permalink", widget: "text", default: "/posts/:categories/:title/"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
  - name: "links" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Links" # Used in the UI, ie.: "New Post"
    description: >
      Links
    folder: "_posts/links"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}/"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Link", name: "link", widget: "string"}      
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Body", name: "body", widget: "text"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "links"}
      - {label: "Categories", name: "categories", widget: "string", default: "link"}
      - {label: "permalink", name: "permalink", widget: "text", default: "/posts/:categories/:title/"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
      
